# Layer config for meta-sbom
# Enables kernel debug-info required by SPDX_INCLUDE_COMPILED_SOURCES

BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "sbom"
BBFILE_PATTERN_sbom = "^${LAYERDIR}/"
BBFILE_PRIORITY_sbom = "10"

LAYERVERSION_sbom = "1"
LAYERSERIES_COMPAT_sbom = "wrynose"
